// <auto-generated />
using System;
using FileProcessing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileProcessing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FileProcessingDbContext))]
    partial class FileProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileProcessing.Core.Domain.ProcessedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("ErrorsTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("errors_truncated");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_rows");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_processed_files_status");

                    b.HasIndex("ClientId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_processed_files_client_received");

                    b.HasIndex("ClientId", "Sha256")
                        .HasDatabaseName("ix_processed_files_client_sha256");

                    b.ToTable("processed_files", (string)null);
                });

            modelBuilder.Entity("FileProcessing.Core.Domain.ProcessingError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<long>("LineNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.Property<Guid>("processed_file_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("processed_file_id")
                        .HasDatabaseName("ix_processing_errors_file");

                    b.ToTable("processing_errors", (string)null);
                });

            modelBuilder.Entity("FileProcessing.Core.Domain.ProcessingError", b =>
                {
                    b.HasOne("FileProcessing.Core.Domain.ProcessedFile", null)
                        .WithMany("Errors")
                        .HasForeignKey("processed_file_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileProcessing.Core.Domain.ProcessedFile", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
