<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>fileprocessing-api-6f1c0f2a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileProcessing.Core\FileProcessing.Core.csproj" />
    <ProjectReference Include="..\FileProcessing.Infrastructure\FileProcessing.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FileProcessing.IntegrationTests" />
  </ItemGroup>

</Project>
