CREATE TABLE IF NOT EXISTS __ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE TABLE processed_files (
        id uuid NOT NULL,
        file_name character varying(255) NOT NULL,
        content_type character varying(128) NOT NULL,
        client_id character varying(64) NOT NULL,
        received_at_utc timestamp with time zone NOT NULL,
        completed_at_utc timestamp with time zone,
        duration_ms bigint NOT NULL,
        status character varying(32) NOT NULL,
        size_bytes bigint NOT NULL,
        sha256 character varying(64) NOT NULL,
        total_rows integer NOT NULL,
        valid_rows integer NOT NULL,
        invalid_rows integer NOT NULL,
        total_amount numeric(18,2) NOT NULL,
        failure_reason character varying(512),
        errors_truncated boolean NOT NULL,
        CONSTRAINT "PK_processed_files" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE TABLE processing_errors (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        line_number bigint NOT NULL,
        code character varying(64) NOT NULL,
        message character varying(512) NOT NULL,
        field character varying(64),
        processed_file_id uuid NOT NULL,
        CONSTRAINT "PK_processing_errors" PRIMARY KEY (id),
        CONSTRAINT "FK_processing_errors_processed_files_processed_file_id" FOREIGN KEY (processed_file_id) REFERENCES processed_files (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE INDEX ix_processed_files_client_received ON processed_files (client_id, received_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE INDEX ix_processed_files_client_sha256 ON processed_files (client_id, sha256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE INDEX ix_processed_files_status ON processed_files (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    CREATE INDEX ix_processing_errors_file ON processing_errors (processed_file_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260828052157_InitialCreate') THEN
    INSERT INTO __ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260828052157_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

